# Generated by Django 3.0 on 2021-08-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brench_id', models.IntegerField(verbose_name='Brench Id')),
                ('sercice_id', models.IntegerField(verbose_name='Service Id')),
                ('channel_id', models.IntegerField(verbose_name='Channel Id')),
            ],
        ),
    ]
