# Generated by Django 3.0 on 2021-08-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sign',
            old_name='sercice_id',
            new_name='service_id',
        ),
    ]
