# Generated by Django 3.0 on 2021-08-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0003_auto_20210820_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='QmaticLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=50, verbose_name='link')),
            ],
        ),
    ]
