# Generated by Django 3.0 on 2021-08-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0004_qmaticlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='channel_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Channel Id'),
        ),
    ]
