# Generated by Django 3.0 on 2021-08-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0005_auto_20210823_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='customer_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer Number'),
        ),
        migrations.AlterField(
            model_name='sign',
            name='channel_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Channel Id'),
        ),
    ]
