# Generated by Django 3.0.7 on 2021-08-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0006_auto_20210823_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='customer_link',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Customer Link'),
        ),
    ]
