# Generated by Django 3.0.7 on 2021-08-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0007_sign_customer_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='QmaticLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.IntegerField(verbose_name='Brench Id')),
                ('service_id', models.IntegerField(verbose_name='Service Id')),
                ('customer_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer Number')),
                ('customer_link', models.CharField(blank=True, max_length=150, null=True, verbose_name='Customer Link')),
                ('transaction_time', models.CharField(max_length=50, verbose_name='Transaction time')),
                ('staff_id', models.CharField(max_length=50, verbose_name='Staff id')),
            ],
        ),
    ]
