# Generated by Django 3.0.7 on 2021-08-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0008_qmaticlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='qmaticlog',
            name='feedback',
            field=models.BooleanField(default=1, verbose_name='Feedback'),
            preserve_default=False,
        ),
    ]
