# Generated by Django 3.0.7 on 2021-08-27 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0009_qmaticlog_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QmaticLink',
        ),
    ]
