# Generated by Django 3.2.6 on 2021-08-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0010_delete_qmaticlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='qmaticlog',
            name='ticked_id',
            field=models.CharField(default=1, max_length=70, verbose_name='Ticket id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qmaticlog',
            name='waiting_time',
            field=models.CharField(default=1, max_length=70, verbose_name='Waiting Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qmaticlog',
            name='transaction_time',
            field=models.CharField(max_length=70, verbose_name='Transaction time'),
        ),
    ]
