# Generated by Django 3.2.6 on 2021-09-01 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0011_auto_20210831_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sign',
            name='customer_link',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='customer_number',
        ),
        migrations.AddField(
            model_name='qmaticlog',
            name='age_range',
            field=models.CharField(default='', max_length=20, verbose_name='Age Range'),
        ),
        migrations.AddField(
            model_name='qmaticlog',
            name='comment',
            field=models.CharField(default='', max_length=1000, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='qmaticlog',
            name='email',
            field=models.CharField(default='', max_length=90, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='qmaticlog',
            name='full_name',
            field=models.CharField(default='', max_length=80, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='qmaticlog',
            name='gender',
            field=models.CharField(default='', max_length=10, verbose_name='Gender'),
        ),
        migrations.CreateModel(
            name='ServiceRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=1500, verbose_name='Service Id')),
                ('rate', models.CharField(max_length=15000, verbose_name='Rate')),
                ('qmatic_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceptance.qmaticlog')),
            ],
        ),
    ]
