# Generated by Django 3.2.6 on 2021-09-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0012_auto_20210901_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qmaticlog',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comment'),
        ),
    ]
