# Generated by Django 3.2.6 on 2021-09-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0013_alter_qmaticlog_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qmaticlog',
            name='age_range',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Age Range'),
        ),
        migrations.AlterField(
            model_name='qmaticlog',
            name='email',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='qmaticlog',
            name='full_name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='qmaticlog',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Gender'),
        ),
    ]
