# Generated by Django 3.2.6 on 2021-09-02 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acceptance', '0014_auto_20210901_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=80, null=True, verbose_name='Full Name')),
                ('email', models.CharField(blank=True, max_length=90, null=True, verbose_name='Email')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='Gender')),
                ('age_range', models.CharField(blank=True, max_length=20, null=True, verbose_name='Age Range')),
                ('comment', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Comment')),
            ],
        ),
        migrations.RemoveField(
            model_name='qmaticlog',
            name='age_range',
        ),
        migrations.RemoveField(
            model_name='qmaticlog',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='qmaticlog',
            name='email',
        ),
        migrations.RemoveField(
            model_name='qmaticlog',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='qmaticlog',
            name='gender',
        ),
        migrations.AddField(
            model_name='qmaticlog',
            name='personal_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acceptance.personalinfo'),
        ),
    ]
